# NUMPY

NUMERICAL PYTHON

In [1]:
# NUMPY IS A MULTIDIRECTIONAL ARRAY LIBRARY.

In [2]:
# EASY TO STORE THE DATA OF 1-D ARRAY, 2-D ARRAY, 3-D ARRAY, 4-D ARRAY, etc.

In [3]:
# NUMPY IS FAST

In [4]:
# NUMPY IS A FIXED TYPE.

In [5]:
# NUMPY USES 4 BYTES OF MEMORY ONLY.

In [6]:
# FASTER TO READ LEASS BYTES OF MEMORY.

In [7]:
# NO TYPE CHECKING WHEN ITERATING THROUGH OBJECT.

In [8]:
# NUMPY USES CONTIGUOUS MEMORY.

In [9]:
# BENEFITS:  

#  1.  SIMD (SINGLE INSTRUCTION MULTIPLE DATA) VECTOR PROCESSING.
#  2.  EFFECTIVE CACHE UTILIZATION.

In [10]:
#  APPLICATIONS OF NUMPY:

#  MATHEMATICS (MATLAB REPLACEMENT)
#  PLOTTING (MATPLOT LIBRARY)
#  BACKEND (PANDAS, CONNECT4, DIGITAL PHOTOGRAPHY)
#  MACHINE LEARNING.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])
total = a*b
print(total)

[ 1  6 15]


In [5]:
import numpy as np
a = np.array([[9,8,7],[6,5,4]])
print(a)
b = np.array([9,7,5])
print(b)

[[9 8 7]
 [6 5 4]]
[9 7 5]


In [6]:
# GET DIMENSION:-

a.ndim

2

In [10]:
# GET SHAPE:-

print(a.shape)
print(b.shape)

(2, 3)
(3,)


In [8]:
# GET TYPE:-

a.dtype

dtype('int32')

In [11]:
# ITEM SIZE:-

a.itemsize

4

In [12]:
# GET TOTAL SIZE:-

a.nbytes

24

In [17]:
# GET THE SPECIFIC ELEMENT (rows, columns):-
print(a)

[[9 8 7]
 [6 5 4]]


In [18]:
a[1,2]

4

In [19]:
# GET A SPECIFIC ROW:-

a[0,:]

array([9, 8, 7])

In [20]:
a[0,]

array([9, 8, 7])

In [22]:
# GET A SPECIFIC COLUMN:-

a[:,2]

array([7, 4])

In [23]:
a[,2]

SyntaxError: invalid syntax (306481597.py, line 1)

In [32]:
# GETTING A LITTLE MORE FANCY [START INDEX : END INDEX : STEP SIZE]

a[0,1 : -1 : 2]

array([8])

In [33]:
a[1,2] = 10
a

array([[ 9,  8,  7],
       [ 6,  5, 10]])

In [34]:
a[:, 2] = [1, 2]
a

array([[9, 8, 1],
       [6, 5, 2]])

3-D EXAMPLE

In [35]:
b = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
# GET SPECIFIC ELEMENT (ROW 1, ROW 2, ... , COLUMN 1, COLUMN 2, ... & SO ON):-

b[0,1,1]

4

In [41]:
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of Arrays:-

In [43]:
np.zeros((2,2))

array([[0, 0],
       [0, 0]])

In [44]:
np.zeros((2,2), dtype = 'int32')

array([[0, 0],
       [0, 0]])

In [45]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [49]:
d = np.ones((6,6), dtype = 'int32')
d

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [50]:
np.full_like(d, 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [51]:
np.full((6,6), 101)

array([[101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101]])

In [52]:
np.random.random_sample(d.shape)

array([[0.07006367, 0.1235018 , 0.51633255, 0.2981672 , 0.47296371,
        0.14167802],
       [0.78980193, 0.55196761, 0.91152595, 0.23209287, 0.82789034,
        0.79434034],
       [0.43212691, 0.22680983, 0.75352141, 0.8428138 , 0.91530712,
        0.03149573],
       [0.0863345 , 0.4896069 , 0.80882642, 0.67603606, 0.18342258,
        0.92046396],
       [0.15863428, 0.35400773, 0.3759503 , 0.03948934, 0.67811735,
        0.18706861],
       [0.00813617, 0.0984852 , 0.43328064, 0.33896777, 0.1931953 ,
        0.28494418]])

In [53]:
np.random.rand(5,8)

array([[0.0657905 , 0.88813503, 0.94195059, 0.97221046, 0.13264699,
        0.27147559, 0.7810865 , 0.43668877],
       [0.26817524, 0.2375723 , 0.8950546 , 0.05927608, 0.19614673,
        0.00339341, 0.97535579, 0.90595037],
       [0.28750662, 0.68448462, 0.24592827, 0.51592717, 0.3811073 ,
        0.39647421, 0.96763504, 0.00153023],
       [0.95892734, 0.73904803, 0.97672214, 0.79920472, 0.69503192,
        0.82339787, 0.91843266, 0.1297136 ],
       [0.84085856, 0.38749722, 0.10176029, 0.06746258, 0.52407897,
        0.38747929, 0.70470085, 0.61886963]])

In [59]:
np.random.randint(4)

3

In [63]:
np.random.randint(9, size = (9,9))

array([[2, 6, 3, 7, 4, 3, 8, 2, 8],
       [6, 2, 7, 4, 8, 2, 2, 6, 2],
       [7, 7, 3, 3, 6, 4, 0, 7, 6],
       [3, 1, 1, 0, 0, 8, 3, 2, 5],
       [4, 3, 3, 4, 7, 1, 2, 3, 7],
       [8, 3, 1, 4, 0, 7, 7, 7, 8],
       [3, 8, 8, 0, 5, 0, 7, 1, 0],
       [0, 6, 2, 5, 4, 7, 0, 1, 7],
       [3, 5, 8, 3, 2, 3, 0, 8, 5]])

In [64]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [65]:
np.identity(8, dtype = 'int32')

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [66]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [70]:
output = np.ones((5,5), dtype = 'int32')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [72]:
zz = np.zeros((3,3), dtype = 'int32')
zz

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
zz = np.zeros((3,3), dtype = 'int32')
zz[1,1] = 9
zz

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [75]:
output[1:4, 1:4] = zz
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [76]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [80]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)          #    THIS IS THE MAIN PROBLEM.....

[100   2   3]
[100   2   3]


In [82]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)          #    THIS IS THE SOLUTION........

[100   2   3]
[1 2 3]


MATHEMATICS:-

In [84]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [85]:
a + 2

array([3, 4, 5, 6])

In [86]:
a - 2

array([-1,  0,  1,  2])

In [87]:
a * 2

array([2, 4, 6, 8])

In [88]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [89]:
b = np.array([3, 9, 3, 9])
b

array([3, 9, 3, 9])

In [90]:
a + b

array([ 4, 11,  6, 13])

In [91]:
a ** 2

array([ 1,  4,  9, 16])

In [92]:
# TAKE THE SIN:-

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [93]:
# TAKE THE COS:-

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [95]:
np

<module 'numpy' from 'C:\\Users\\HP\\Desktop\\Anaconda\\lib\\site-packages\\numpy\\__init__.py'>

In [96]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

LINEAR ALGEBRA:-

In [100]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
b = np.full((3,3), 2)
b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [106]:
np.matmul(a,b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [109]:
c = np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
stats = np.array([[1,2,3], [4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [112]:
np.min(stats)

1

In [113]:
np.max(stats)

6

In [115]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [116]:
np.max(stats, axis = 1)

array([3, 6])

In [117]:
np.sum(stats)

21

In [118]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [119]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [120]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [121]:
# OR

after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [123]:
V1 = np.array([1,2,3,4])
V2 = np.array([5,6,7,8])

np.stack([V1, V2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
np.stack([V1, V2, V2, V1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [128]:
H1 = np.ones([2,4])
H2 = np.zeros([2,2])

np.hstack((H1, H2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [129]:
# LOAD THE DATA FROM FILE:-

In [130]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([44,  3,  3,  3,  4,  5,  3, 23, 23, 55,  4,  3,  8,  9,  8, 88, 99,
       67,  5])

In [131]:
filedata[filedata > 50]

array([55, 88, 99, 67])

In [132]:
np.any(filedata > 50, axis = 0)

True

In [133]:
np.all(filedata > 50, axis = 0)

False

In [134]:
((filedata > 50) & (filedata <100))

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True,  True,  True,
       False])

In [137]:
(~((filedata > 50) & (filedata <100)))     #  ~ means  not.

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
        True])

In [7]:
import numpy as np
i = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [8]:
i[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [9]:
i[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [11]:
i[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
  
# view array
print(arr)
  
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [17]:
# declare matrix with np
g = np.array([[6, 9], [8, 5], [18, 21]])
g

array([[ 6,  9],
       [ 8,  5],
       [18, 21]])

In [18]:
# declare matrix with np
g = np.array([[6, 9], [8, 5], [18, 21]])
  
# using array.flatten() method
g.flatten()

array([ 6,  9,  8,  5, 18, 21])